# Importing Libraries

In [1]:
import pandas as pd 

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [2]:
df_games = pd.read_csv("../artifacts/raw_data/results.csv")
df_ranking = pd.read_csv("../artifacts/raw_data/wc_2026_48_teams_fifa_rank_change.csv")
df_group_stage = pd.read_csv("../artifacts/raw_data/group_stages.csv", sep=";")
df_knockout_fixtures = pd.read_csv("../artifacts/raw_data/fixtures_knockout_wc2026.csv")

# Basic Statistics

##  All Games since 1872

Our main dataset consists of all matches from 1872 to till date. It has been already updated with FIFA World Cup 2026 schedule. When we are cleaning the data set we need to separate it as we need the match details in order to predict the FIFA World cup results. Lets see some of the basic statistics of the dataset.

In [3]:
df_games.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [4]:
df_games.tail()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
49472,2026-06-27,Jordan,Argentina,NaN,NaN,FIFA World Cup,Arlington,United States,True
49473,2026-06-27,Colombia,Portugal,NaN,NaN,FIFA World Cup,Miami Gardens,United States,True
49474,2026-06-27,DR Congo,Uzbekistan,NaN,NaN,FIFA World Cup,Atlanta,United States,True
49475,2026-06-27,Panama,England,NaN,NaN,FIFA World Cup,East Rutherford,United States,True
49476,2026-06-27,Croatia,Ghana,NaN,NaN,FIFA World Cup,Philadelphia,United States,True

In [5]:
df_games.shape

(49477, 9)

In [6]:
df_games.info()

<class 'pandas.DataFrame'>
RangeIndex: 49477 entries, 0 to 49476
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        49477 non-null  str
 1   home_team   49477 non-null  str
 2   away_team   49477 non-null  str
 3   home_score  49425 non-null  float64
 4   away_score  49425 non-null  float64
 5   tournament  49477 non-null  str
 6   city        49477 non-null  str
 7   country     49477 non-null  str
 8   neutral     49477 non-null  bool
dtypes: bool(1), float64(2), str(6)
memory usage: 5.9 MB

In [7]:
df_games.columns

Index(['date', 'home_team', 'away_team', 'home_score', 'away_score',
       'tournament', 'city', 'country', 'neutral'],
      dtype='str')

In [8]:
df_games.isnull().sum()

date           0
home_team      0
away_team      0
home_score    52
away_score    52
tournament     0
city           0
country        0
neutral        0
dtype: int64

In [9]:
df_games.describe()

         home_score    away_score
count  49425.000000  49425.000000
mean       1.757390      1.181851
std        1.774267      1.401910
min        0.000000      0.000000
25%        1.000000      0.000000
50%        1.000000      1.000000
75%        2.000000      2.000000
max       31.000000     21.000000

In [10]:
df_games.duplicated().sum()

np.int64(0)

In [11]:
df_games.apply(lambda x : len(x.unique()))

date          16471
home_team       327
away_team       321
home_score       27
away_score       23
tournament      200
city           2089
country         269
neutral           2
dtype: int64

## FIFA Ranking in 2022 and 2026

In [12]:
df_ranking.head()

      Nation  FIFA_2022_ranking  FIFA_2026_rank  rank_change
0     France                  3               1            2
1      Spain                 10               2            8
2  Argentina                  2               3           -1
3    England                  5               4            1
4   Portugal                  9               5            4

In [13]:
df_ranking.shape

(48, 4)

In [14]:
df_ranking['Nation'].unique()

<ArrowStringArray>
[                'France',                  'Spain',              'Argentina',
                'England',               'Portugal',                 'Brazil',
            'Netherlands',                'Morocco',                'Belgium',
                'Germany',                'Croatia',               'Colombia',
                'Senegal',                 'Mexico',          'United States',
                'Uruguay',                  'Japan',            'Switzerland',
                   'Iran',                 'Turkey',                'Ecuador',
                'Austria',            'South Korea',              'Australia',
                'Algeria',                  'Egypt',                 'Canada',
                 'Norway',                 'Panama',            'Ivory Coast',
                 'Sweden',               'Paraguay',         'Czech Republic',
               'Scotland',                'Tunisia',               'DR Congo',
             'Uzbekistan',                  'Qatar',                   'Iraq',
           'South Africa',           'Saudi Arabia',                 'Jordan',
 'Bosnia and Herzegovina',             'Cape Verde',                  'Ghana',
                'Curaçao',                  'Haiti',            'New Zealand']
Length: 48, dtype: str

In [15]:
df_ranking.tail()

         Nation  FIFA_2022_ranking  FIFA_2026_rank  rank_change
43   Cape Verde                 72              69            3
44        Ghana                 58              74          -16
45      Curaçao                 86              82            4
46        Haiti                 87              83            4
47  New Zealand                105              85           20

In [16]:
df_ranking.info()

<class 'pandas.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Nation             48 non-null     str
 1   FIFA_2022_ranking  48 non-null     int64
 2   FIFA_2026_rank     48 non-null     int64
 3   rank_change        48 non-null     int64
dtypes: int64(3), str(1)
memory usage: 2.0 KB

In [17]:
df_ranking.isnull().sum()

Nation               0
FIFA_2022_ranking    0
FIFA_2026_rank       0
rank_change          0
dtype: int64

In [18]:
df_ranking.duplicated().sum()

np.int64(0)

## Group Stages Fixtures

In [19]:
df_group_stage.head()

  group  position          nation
0     A         1          Mexico
1     A         2    South Africa
2     A         3     South Korea
3     A         4  Czech Republic
4     B         1          Canada

In [20]:
df_group_stage.shape

(48, 3)

In [21]:
df_group_stage.tail()

   group  position    nation
43     K         4  Colombia
44     L         1   England
45     L         2   Croatia
46     L         3     Ghana
47     L         4    Panama

In [22]:
df_group_stage.info()

<class 'pandas.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   group     48 non-null     str
 1   position  48 non-null     int64
 2   nation    48 non-null     str
dtypes: int64(1), str(2)
memory usage: 1.7 KB

## Knockout Fixtures

In [23]:
df_knockout_fixtures.head()

,match_id,round,match_date,match_time,home_slot,away_slot,winner_advances_to,loser_advances_to
0,M73,R32,2026-06-28,20:00,2A,2B,M90,NaN
1,M74,R32,2026-06-29,21:30,1E,3ABCDF,M89,NaN
2,M75,R32,2026-06-30,02:00,1F,2C,M90,NaN
3,M76,R32,2026-06-29,18:00,1C,2F,M91,NaN
4,M77,R32,2026-06-30,22:00,1I,3CDFGH,M89,NaN

In [24]:
df_knockout_fixtures.shape

(32, 8)

In [25]:
df_knockout_fixtures.tail()

,match_id,round,match_date,match_time,home_slot,away_slot,winner_advances_to,loser_advances_to
27,M100,QF,2026-07-12,02:00,W95,W96,M102,NaN
28,M101,SF,2026-07-14,20:00,W97,W98,M104,M103
29,M102,SF,2026-07-15,20:00,W99,W100,M104,M103
30,M103,3rd,2026-07-18,22:00,RU101,RU102,NaN,NaN
31,M104,Final,2026-07-19,20:00,W101,W102,NaN,NaN

All the dataset seems to be clean we just need basic cleaning of dataset before moving to the feature engineering.