# Importing Libraries

In [1]:
import pandas as pd 

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [2]:
df = pd.read_csv("../artifacts/raw_data/results.csv")

# Basic Statistics

In [3]:
df.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [4]:
df.tail()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
49472,2026-06-27,Jordan,Argentina,NaN,NaN,FIFA World Cup,Arlington,United States,True
49473,2026-06-27,Colombia,Portugal,NaN,NaN,FIFA World Cup,Miami Gardens,United States,True
49474,2026-06-27,DR Congo,Uzbekistan,NaN,NaN,FIFA World Cup,Atlanta,United States,True
49475,2026-06-27,Panama,England,NaN,NaN,FIFA World Cup,East Rutherford,United States,True
49476,2026-06-27,Croatia,Ghana,NaN,NaN,FIFA World Cup,Philadelphia,United States,True

In [5]:
df.shape

(49477, 9)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 49477 entries, 0 to 49476
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        49477 non-null  str
 1   home_team   49477 non-null  str
 2   away_team   49477 non-null  str
 3   home_score  49425 non-null  float64
 4   away_score  49425 non-null  float64
 5   tournament  49477 non-null  str
 6   city        49477 non-null  str
 7   country     49477 non-null  str
 8   neutral     49477 non-null  bool
dtypes: bool(1), float64(2), str(6)
memory usage: 5.9 MB

In [7]:
df.columns

Index(['date', 'home_team', 'away_team', 'home_score', 'away_score',
       'tournament', 'city', 'country', 'neutral'],
      dtype='str')

In [8]:
df.isnull().sum()

date           0
home_team      0
away_team      0
home_score    52
away_score    52
tournament     0
city           0
country        0
neutral        0
dtype: int64

In [9]:
df.describe()

         home_score    away_score
count  49425.000000  49425.000000
mean       1.757390      1.181851
std        1.774267      1.401910
min        0.000000      0.000000
25%        1.000000      0.000000
50%        1.000000      1.000000
75%        2.000000      2.000000
max       31.000000     21.000000

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.apply(lambda x : len(x.unique()))

date          16471
home_team       327
away_team       321
home_score       27
away_score       23
tournament      200
city           2089
country         269
neutral           2
dtype: int64